package model;

/**
 * Created by Boris on 26-Sep-16.
 */
public enum Command {
    JUMPIN, GETOUT, EXP, SHOWEXP, DELEXP, CALC, CALCTOTAL, HELP, START, UPDATENAME, SHOWTRAVELERS, FUND, DELFUND, CREDIT, SHOWFUNDED, EXCLUDE, UPDATE, CALCTOTALAVERAGE, FINALIZE, UPDATETOKEN
}
